

services:
  postgres:
    image: "postgres:13.12"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pAssw0rd
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres
     networks:
       be_ecommerce_network:
         ipv4_address: 10.0.0.15
   api_server:
     image: "backend"
     build:
       context: .
       dockerfile: ./Dockerfile
     networks:
        be_ecommerce_network:
         ipv4_address: 10.0.0.14

 networks:
   be_ecommerce_network:
     driver: bridge
     ipam:
       driver: default
       config:
         - subnet: 10.0.0.0/16
        